language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - nightly
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
