language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  - DEPENDENCIES="--prefer-lowest --prefer-stable"
  - DEPENDENCIES=""

before_script:
  - travis_retry composer update --prefer-dist $DEPENDENCIES

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
