language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
