language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - DEPENDENCIES="--prefer-lowest --prefer-stable"
  - DEPENDENCIES=""

before_script:
  - travis_retry composer update --prefer-dist $DEPENDENCIES

script:
  - ./vendor/bin/phpunit --coverage-clover ./clover.xml
  - php examples/persisting-new-objects-in-batch.php > /dev/null
  - php examples/working-with-query-resultsets-in-batch.php > /dev/null
